- Display/pathfinder/feat.html.twig
- Display/pathfinder/spell.html.twig
- Schema/pathfinder/feat.yml
- Schema/pathfinder/spell.yml
- css/pathfinder/pathfinder.css
Added Pathfinder Spell and Feat blocks
Added pathfinder CSS (copied from dnd5e with a few changes)
> Added basics for pathfinder blocks

- Schema/sw/sw_armor.yml
- Schema/sw/sw_creature.yml
- Schema/sw/sw_item.yml
- Schema/sw/sw_power.yml
- Schema/sw/sw_vehicle.yml
- Schema/sw/sw_weapon_melee.yml
- Schema/sw/sw_weapon_range.yml
- Added various missing labels
- Fixed a duplicate field
- Fixed some typos in the input types
> Several fixes to Savage Worlds Schemata

- Schema/genesys/adversary.yml
- Schema/genesys/archetype.yml
- Schema/genesys/minion.yml
@iamromeo here are the requested descriptions.
> Added descriptions to ability fields for genesys templates.

- css/genesys/genesys.css
Added background image to Genesys block.
> Genesys block bg

- css/genesys/genesys.css
> Genesys statblock width fix

- Display/l5r/npc.html.twig
- Display/l5r/pc.html.twig
Bolded stat headers and moved divs for css around a bit.
> Styling updates

- Schema/genesys/adversary.yml
- Schema/genesys/archetype.yml
- Schema/genesys/minion.yml
@iamromeo I think this is appropriate since genesys statblocks aren't designed to have tables, right?
> Set table: false in genesys schemas.

- Display/genesys/career.html.twig
- Schema/genesys/career.yml
- css/genesys/genesys.css
@iamromeo here is the block for Genesys careers.
> Added Genesys Career block

- Display/genesys/talent.html.twig
- Schema/genesys/talent.yml
- css/genesys/genesys.css
@iamromeo and here's talents! :D
> Added genesys talent block.

- Display/genesys/talent.html.twig
@iamromeo I forgot to apply an important class in the Telent HTML. :x
> Fixed issue where not all styling was being applied to Genesys talent blocks.

- Display/genesys/adversary.html.twig
- Display/genesys/archetype.html.twig
- Display/genesys/career.html.twig
- Display/genesys/minion.html.twig
- Display/genesys/talent.html.twig
- css/genesys/genesys.css
@iamromeo minor refactor of genesys styling to make things a bit more flexible and easy to use. This depends on #20 .
> Genesys css refactor

- Schema/genesys/character-sheet.yml
-Made most fields not mandatory for testing purposes.
-Fixed Cool.
-Fixed Knowledge.
-Added Perception
> Updates and removals of some

- themes/darkly/css/style.css
Note  to self; don't work at 5 am.
> IMPORTANT! Linked the wrong folder

- themes/darkly/css/style.css
Fixed a few small tweaks but primarily updated the headers to actually look like headers.
> Update: Your World, Darkly

- Schema/dnd35e/character.yml
- Schema/dnd5e/character.yml
> adding 3.5 

- Display/dnd35e/character.html.twig
> Variable Security 

- Display/dnd35e/character.html.twig
- Fixing row bug 
- fixing  missing closing ]
> Fixing minors bugs

- Display/dnd35e/character.html.twig
adding the attacks to the template :)
> [D&D 3.5e]  Fixing missing combat section

- css/genesys/genesys.css
- css/genesys/genesys.css : fixed divs positions
> [genesys] Fixed Character Sheet CSS

- themes/galaxyanvil/css/style.css
**Added**
- Styling for the `.map-box` class
- Styling for all `.alert` boxes, including those outside of `.user-css` spaces
> GalaxyAnvil v1.1.0

- themes/galaxyanvil/css/style.css
Hotfix:
- Character sheet text is now black instead of bright pink on a white background. Temporary fix until proper support for character sheets is added.
> GalaxyAnvil v1.1.1

- themes/notebook/css/style.css
Organized, refined, beautiful. Something something tagline about the product. No one reads these, but if they did, they would be stunned. I think Tesla was a pretty okay guy. I don't have any notebooks that look like this name even though it is named Notebook.
> Notebook V2.0

- Display/cod/character-pth.html.twig
- Schema/cod/character-pth.yml
- Schema/cod/character-vtr.yml
[cod] finished preliminary pth sheet and fixed a typo in .yml files
* Schema/cod/character-pth.yml: modified skills, tables, secondary stats, and other stats
* Schema/cod/character-pth.yml: fixed typo in skills (mac changed to max)
* Schema/cod/character-vtr.yml: fixed typo in skills (mac changed to max)
* Display/cod/character-pth.html.twig: added block char_advanctages
> Batch 27/09/2018

- Display/lostcol/character.html.twig
- Display/lostcol/scar.html.twig
- Display/lostcol/skill.html.twig
- Schema/lostcol/character.yml
- Schema/lostcol/scar.yml
- Schema/lostcol/skill.yml
- Schema/lostcol/character.yml
- Schema/lostcol/skill.yml
> [WIP][lostcol] First cut

- themes/opulent/css/style.css
Makes it actually readable. I just stole the base font color and applied it. Don't murder me, TJ.
> Comment Section Text Area

- themes/galaxyanvil/CHANGELOG.MD
- themes/galaxyanvil/css/style.css
I give up on tracking version numbers.
- Support for WorldAnvil's new world presentation front page
- Support for Organization Tree
- Support for article tooltipster previews
- Tweaked small and muted text color to improve readability.
- Changed backgrounds of various elements to use the metallic gradient style instead of a flat transparency
- Search icon color not overriding default WA styles in inline version.
- Tag labels in timelines not being colored.
> GalaxyAnvil Update

- themes/darkly/css/style.css
> Statblock Background Fix

- newcomers-guide.md
- statblock-cheatsheet.md
updated files : 
- Statblock cheatsheet
> Documentation update to reflect block system 2.0

- block-system-2.0/dnd5e/character-2020/dnd5e-badge.twig
- block-system-2.0/dnd5e/character-2020/dnd5e-form.html.twig
- block-system-2.0/dnd5e/character-2020/dnd5e-sheet.html.twig
- block-system-2.0/dnd5e/character-2020/dnd5e-trackable.html.twig
- block-system-2.0/dnd5e/character-2020/schema.yml
- Update 5e sheets to properly calculate HP based on the different hit dice per class.
- Introducing a new field hit_points_first for the hit points on character creation, as these are different from every other level.
- Update schema.yml to reflect the current fields of the form.
> fix hp calculation, update schema

- block-system-2.0/advanced-5e/character/basic.html.twig
- block-system-2.0/advanced-5e/character/form.html.twig
- block-system-2.0/advanced-5e/character/style.css
- block-system-2.0/cyberpunk/2020/character-sheet/character.sheet.css
- block-system-2.0/cyberpunk/2020/character-sheet/display.html.twig
- block-system-2.0/cyberpunk/2020/character-sheet/form.html.twig
- block-system-2.0/cyberpunk/2020/character-sheet/parts.yml
- block-system-2.0/cyberpunk/2020/character-sheet/raw.css
- block-system-2.0/cyberpunk/2020/character-sheet/tracker.html.twig
- block-system-2.0/dnd5e/monster-2020/form.html.twig
- block-system-2.0/dnd5e/monster-2020/sheet.html.twig
- block-system-2.0/dnd5e/npc-2020/form.html.twig
- block-system-2.0/dnd5e/npc-2020/sheet.html.twig
- block-system-2.0/pathfinder_2/feat/feat.css
- block-system-2.0/pathfinder_2/item/item.css
- block-system-2.0/pathfinder_2/kingdom/kingdom.css
- block-system-2.0/pathfinder_2/monster/monster.css
- block-system-2.0/pathfinder_2/spell/spell.css
- block-system-2.0/valiant_rpg_system/character/basic.html.twig
- block-system-2.0/valiant_rpg_system/character/form.html.twig
- block-system-2.0/valiant_rpg_system/character/style.css
- new: [cp2020]
- enhancements: [dnd5e] monster, npc
- fixes: [pf2e] stat block dark mode
- fixes: [tov], [a5e] armor dex bonus
> updates and new sheets

- block-system-2.0/outgunned/character/approved.css
- block-system-2.0/outgunned/character/badge.html.twig
- block-system-2.0/outgunned/character/basic-sheet.html.twig
- block-system-2.0/outgunned/character/edit-form.html.twig
- block-system-2.0/outgunned/character/import-to-wa.yml
- block-system-2.0/outgunned/character/sheet.css
- block-system-2.0/outgunned/character/tracker.html.twig
- tools/backup/backup.py
- tools/backup/readme.md
- tools/yaml_to_sheet/gen.py
- Update Backup script
- Update Yaml2Sheet script
- Outgunned character sheet
> Misc changes

- block-system-2.0/cosmere_rpg/character/approved.css
- block-system-2.0/cosmere_rpg/character/badge.html.twig
- block-system-2.0/cosmere_rpg/character/basic-sheet.html.twig
- block-system-2.0/cosmere_rpg/character/edit-form.html.twig
- block-system-2.0/cosmere_rpg/character/import-to-wa.yml
- block-system-2.0/cosmere_rpg/character/include/data.twig
- block-system-2.0/cosmere_rpg/character/include/footer.twig
- block-system-2.0/cosmere_rpg/character/include/header.twig
- block-system-2.0/cosmere_rpg/character/schema.yml
- block-system-2.0/cosmere_rpg/character/sheet.css
- block-system-2.0/cosmere_rpg/character/tracker.html.twig
- block-system-2.0/cypher/character-sheet/display.html.twig
- block-system-2.0/dnd5e/character-2020/dnd5e-badge.twig
- block-system-2.0/dnd5e/character-2020/dnd5e-trackable.html.twig
- block-system-2.0/outgunned/character/basic-sheet.html.twig
- tools/backup/readme.md
- tools/backup/settings.cfg
- new system Cosmere RPG
- fixes for Outgunned and Cypher
> [cosmere-rpg] et al
